version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_DATABASE=users
      - TYPEORM_USER=postgres
      - TYPEORM_PASSWORD=root
      - TYPEORM_PORT=5432
      - TYPEORM_ENTITIES=src/**/**.entity.ts
      - JWT_SECRET=test
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports: 
      - 5432:5432
    restart: always